# Generated by Django 5.0.4 on 2024-05-06 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("LocationManagement", "0005_alter_regions_valid_till"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodStyle",
            fields=[
                ("status", models.BooleanField(default=True)),
                (
                    "valid_till",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 6, 19, 8, 50, 461667, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("avatar", models.URLField()),
                ("description", models.TextField()),
                ("data", models.JSONField()),
                (
                    "region",
                    models.ManyToManyField(
                        related_name="food_style", to="LocationManagement.regions"
                    ),
                ),
            ],
            options={
                "db_table": "FOODSTYLE",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("status", models.BooleanField(default=True)),
                (
                    "valid_till",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 6, 19, 8, 50, 461667, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("avatar", models.URLField()),
                ("description", models.TextField()),
                ("data", models.JSONField()),
                (
                    "food_style",
                    models.ManyToManyField(
                        related_name="category", to="CloudKit.foodstyle"
                    ),
                ),
            ],
            options={
                "db_table": "CATEGORY",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("status", models.BooleanField(default=True)),
                (
                    "valid_till",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 6, 19, 8, 50, 461667, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("avatar", models.URLField()),
                ("description", models.TextField()),
                ("data", models.JSONField()),
                (
                    "category",
                    models.ManyToManyField(related_name="meal", to="CloudKit.category"),
                ),
            ],
            options={
                "db_table": "MEAL",
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("status", models.BooleanField(default=True)),
                (
                    "valid_till",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 6, 19, 8, 50, 461667, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("number_of_units", models.IntegerField()),
                ("unit_price", models.IntegerField()),
                ("avatar", models.URLField()),
                ("description", models.TextField()),
                ("data", models.JSONField()),
                (
                    "meal",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="CloudKit.meal"
                    ),
                ),
            ],
            options={
                "db_table": "ITEMS",
            },
        ),
    ]
