# Generated by Django 4.2.1 on 2024-06-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKit', '0012_meal_rating_alter_category_valid_till_and_more'),
        ('SupportManagement', '0002_alter_ticketingsystem_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportexperience',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CloudKit.meal'),
            preserve_default=False,
        ),
    ]
