# Generated by Django 5.0.4 on 2024-05-06 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 6, 19, 7, 27, 987419, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
