# Generated by Django 4.2.1 on 2024-05-19 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 5, 19, 7, 29, 41, 875288, tzinfo=datetime.timezone.utc)),
        ),
    ]
