# Generated by Django 4.2.1 on 2024-06-17 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 6, 17, 17, 12, 14, 902702, tzinfo=datetime.timezone.utc)),
        ),
    ]
