# Generated by Django 5.1 on 2024-08-17 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 8, 17, 14, 48, 36, 262720, tzinfo=datetime.timezone.utc)),
        ),
    ]
