# Generated by Django 5.0.4 on 2024-05-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regions",
            fields=[
                ("status", models.BooleanField(default=True)),
                (
                    "valid_till",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 6, 19, 4, 39, 487832, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "REGIONS",
            },
        ),
    ]
