# Generated by Django 5.0.4 on 2024-05-06 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LocationManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regions",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 6, 19, 5, 51, 150616, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
