# Generated by Django 4.2.1 on 2024-05-19 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationManagement', '0012_alter_regions_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 5, 19, 8, 43, 5, 947087, tzinfo=datetime.timezone.utc)),
        ),
    ]
