# Generated by Django 4.2.1 on 2024-06-23 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationManagement', '0017_alter_regions_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 16, 5, 27, 331370, tzinfo=datetime.timezone.utc)),
        ),
    ]
