# Generated by Django 5.1 on 2024-08-17 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationManagement', '0019_alter_regions_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 8, 17, 14, 48, 36, 273871, tzinfo=datetime.timezone.utc)),
        ),
    ]
